In [3]:
import joblib

model = joblib.load("tuned_xgboost.pkl")
model

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=np.float64(0.9819121786756363), device=None,
             early_stopping_rounds=None, enable_categorical=True,
             eval_metric=None, feature_types=None, feature_weights=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None,
             learning_rate=np.float64(0.08781417857605588), max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=2, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=200, n_jobs=None,
             num_parallel_tree=None, ...)

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("feature_engineered.csv")

df["date"] = pd.to_datetime(df["date"])
df = df.set_index("date")
df = df.dropna()

df.head()

,unit_sales,year,month,day,day_of_week,week_of_year,quarter,is_weekend,lag_1,lag_7,lag_14,lag_30,rolling_mean_7,rolling_mean_30,rolling_std_7,rolling_std_30,dcoilwtico,is_holiday
date,,,,,,,,,,,,,,,,,,
2013-02-01,401.0,2013,2,1,4,5,1,0,282.0,389.0,60.0,582.0,456.285714,514.800000,153.272866,238.098849,97.46,False
2013-02-02,775.0,2013,2,2,5,5,1,1,401.0,697.0,667.0,310.0,467.428571,530.300000,174.986530,239.438589,97.46,False
2013-02-03,855.0,2013,2,3,6,5,1,1,775.0,616.0,1090.0,338.0,501.571429,547.533333,224.981375,243.688288,97.46,False
2013-02-04,411.0,2013,2,4,0,6,1,0,855.0,318.0,760.0,654.0,514.857143,539.433333,214.852219,244.065662,96.21,False
2013-02-05,272.0,2013,2,5,1,6,1,0,411.0,393.0,461.0,979.0,497.571429,515.866667,230.581769,234.087625,96.68,False

In [5]:
df.columns

Index(['unit_sales', 'year', 'month', 'day', 'day_of_week', 'week_of_year',
       'quarter', 'is_weekend', 'lag_1', 'lag_7', 'lag_14', 'lag_30',
       'rolling_mean_7', 'rolling_mean_30', 'rolling_std_7', 'rolling_std_30',
       'dcoilwtico', 'is_holiday'],
      dtype='object')

In [6]:
last_row = df.drop(columns=["unit_sales"]).iloc[-1:]

last_row

,year,month,day,day_of_week,week_of_year,quarter,is_weekend,lag_1,lag_7,lag_14,lag_30,rolling_mean_7,rolling_mean_30,rolling_std_7,rolling_std_30,dcoilwtico,is_holiday
date,,,,,,,,,,,,,,,,,
2014-03-31,2014,3,31,0,14,1,0,599.0,371.0,285.0,714.0,476.571429,450.5,116.328353,144.597599,101.57,False

In [7]:
prediction = model.predict(last_row)

print(prediction)

[430.71783]

In [8]:
def predict_latest_sales():
    last_row = df.drop(columns=["unit_sales"]).iloc[-1:]
    prediction = model.predict(last_row)[0]
    return prediction

latest_prediction = predict_latest_sales()

print(f"Predicted unit sales: {latest_prediction:.2f}")

Predicted unit sales: 430.72